/**
 * Textes éditables depuis /admin/textes.
 */
export const TEXTES_DEFAUT: {
  cle: string;
  page: string;
  label: string;
  valeur: string;
}[] = [
  // Accueil
  { cle: "accueil.badge", page: "Accueil", label: "Hero — pastille", valeur: "Naturopathie & massage bien-être" },
  { cle: "accueil.h1", page: "Accueil", label: "Hero — titre", valeur: "Prendre soin de soi, en douceur et en confiance" },
  { cle: "accueil.sous_titre", page: "Accueil", label: "Hero — sous-titre", valeur: "au service de la femme" },
  { cle: "accueil.intro", page: "Accueil", label: "Hero — introduction", valeur: "Consultations de naturopathie en visio, massages bien-être à domicile pour vous et pour bébé, des ateliers de langue des signes française. Une parenthèse de douceur, chez vous." },
  { cle: "accueil.cta1", page: "Accueil", label: "Hero — bouton 1", valeur: "Réserver une consultation" },
  { cle: "accueil.cta2", page: "Accueil", label: "Hero — bouton 2", valeur: "Découvrir les massages" },
  { cle: "accueil.pastille_visio", page: "Accueil", label: "Hero — pastille visio", valeur: "Lien visio envoyé automatiquement après paiement" },
  { cle: "accueil.pastille_paiement", page: "Accueil", label: "Hero — pastille paiement", valeur: "Paiement en ligne sécurisé" },
  { cle: "accueil.pastille_rappel", page: "Accueil", label: "Hero — pastille rappel", valeur: "Rappel la veille" },
  { cle: "accueil.univers_eyebrow", page: "Accueil", label: "Deux univers — petit titre", valeur: "Deux univers" },
  { cle: "accueil.univers_titre", page: "Accueil", label: "Deux univers — titre", valeur: "Une même attention, deux façons de prendre soin de vous" },
  { cle: "accueil.univers_sous", page: "Accueil", label: "Deux univers — texte", valeur: "La naturopathie soutient votre vitalité de l'intérieur ; le massage relâche, enveloppe et accompagne. Deux pratiques réunies dans un seul espace, sans les confondre." },
  { cle: "accueil.card_naturo_badge", page: "Accueil", label: "Carte naturo — pastille", valeur: "au service de la femme" },
  { cle: "accueil.card_naturo_titre", page: "Accueil", label: "Carte naturo — titre", valeur: "Naturopathie — en visio" },
  { cle: "accueil.card_naturo_texte", page: "Accueil", label: "Carte naturo — texte", valeur: "Bilan de vitalité, conseils d'hygiène de vie et suivi personnalisé, où que vous soyez." },
  { cle: "accueil.card_naturo_l1", page: "Accueil", label: "Carte naturo — puce 1", valeur: "Premier rendez-vous de 1h30, puis suivis d'1h" },
  { cle: "accueil.card_naturo_l2", page: "Accueil", label: "Carte naturo — puce 2", valeur: "Lien visio envoyé automatiquement après paiement" },
  { cle: "accueil.card_naturo_l3", page: "Accueil", label: "Carte naturo — puce 3", valeur: "Rappel la veille, sans démarche de votre côté" },
  { cle: "accueil.card_naturo_lien", page: "Accueil", label: "Carte naturo — lien", valeur: "Découvrir la naturopathie" },
  { cle: "accueil.card_massage_titre", page: "Accueil", label: "Carte massage — titre", valeur: "Massage — à domicile" },
  { cle: "accueil.card_massage_texte", page: "Accueil", label: "Carte massage — texte", valeur: "Prénatal, postnatal, bébé — je me déplace chez vous avec tout le matériel." },
  { cle: "accueil.card_massage_l1", page: "Accueil", label: "Carte massage — puce 1", valeur: "Tarif kilométrique transparent et calculé pour vous" },
  { cle: "accueil.card_massage_l2", page: "Accueil", label: "Carte massage — puce 2", valeur: "Forfait bébé 4 séances ou séance à l'unité" },
  { cle: "accueil.card_massage_l3", page: "Accueil", label: "Carte massage — puce 3", valeur: "Tout le matériel est prévu" },
  { cle: "accueil.card_massage_lien", page: "Accueil", label: "Carte massage — lien", valeur: "Découvrir les massages" },
  { cle: "accueil.pratique_eyebrow", page: "Accueil", label: "En pratique — petit titre", valeur: "En pratique" },
  { cle: "accueil.pratique_titre", page: "Accueil", label: "En pratique — titre", valeur: "Comment ça se passe ?" },
  { cle: "accueil.etape1_titre", page: "Accueil", label: "Étape 1 — titre", valeur: "Vous choisissez votre soin" },
  { cle: "accueil.etape1_texte", page: "Accueil", label: "Étape 1 — texte", valeur: "Consultation, massage ou atelier : vous trouvez la formule qui vous ressemble, avec des tarifs clairs." },
  { cle: "accueil.etape2_titre", page: "Accueil", label: "Étape 2 — titre", valeur: "Vous réservez votre créneau" },
  { cle: "accueil.etape2_texte", page: "Accueil", label: "Étape 2 — texte", valeur: "Les disponibilités s'affichent en temps réel. Pour un massage, le supplément kilométrique est calculé automatiquement depuis votre adresse." },
  { cle: "accueil.etape3_titre", page: "Accueil", label: "Étape 3 — titre", valeur: "Vous réglez en ligne" },
  { cle: "accueil.etape3_texte", page: "Accueil", label: "Étape 3 — texte", valeur: "Paiement intégral sécurisé à la réservation. Simple et sans surprise." },
  { cle: "accueil.etape4_titre", page: "Accueil", label: "Étape 4 — titre", valeur: "Vous êtes accompagnées" },
  { cle: "accueil.etape4_texte", page: "Accueil", label: "Étape 4 — texte", valeur: "Confirmation immédiate, lien visio envoyé automatiquement et rappel la veille. Il ne reste qu'à profiter." },
  { cle: "accueil.km_badge", page: "Accueil", label: "Kilomètres — pastille", valeur: "Déplacements" },
  { cle: "accueil.km_titre", page: "Accueil", label: "Kilomètres — titre", valeur: "Des kilomètres clairs, sans surprise" },
  { cle: "accueil.km_texte", page: "Accueil", label: "Kilomètres — texte", valeur: "Les 15 premiers kilomètres sont inclus dans le prix de la séance. Au-delà, le supplément est de 0,55 € par kilomètre, calculé automatiquement depuis votre adresse lors de la réservation. Vous connaissez le montant exact avant de confirmer." },
  { cle: "accueil.km_cta1", page: "Accueil", label: "Kilomètres — bouton 1", valeur: "Voir la zone de déplacement" },
  { cle: "accueil.km_cta2", page: "Accueil", label: "Kilomètres — bouton 2", valeur: "Les massages" },
  { cle: "accueil.km_apercu", page: "Accueil", label: "Kilomètres — encadré aperçu", valeur: "Aperçu du supplément" },
  { cle: "accueil.lsf_badge", page: "Accueil", label: "Bloc LSF — pastille", valeur: "Atelier bébé signes" },
  { cle: "accueil.lsf_titre", page: "Accueil", label: "Bloc LSF — titre", valeur: "Parler avec bébé avant les mots" },
  { cle: "accueil.lsf_texte", page: "Accueil", label: "Bloc LSF — texte", valeur: "L'atelier de langue des signes française pour bébé vous donne les signes essentiels du quotidien — besoins, émotions, envies — pour communiquer avec votre tout-petit dès ses premiers mois." },
  { cle: "accueil.lsf_l1", page: "Accueil", label: "Bloc LSF — puce 1", valeur: "À domicile, en collectif ou en visio" },
  { cle: "accueil.lsf_l2", page: "Accueil", label: "Bloc LSF — puce 2", valeur: "Supports vidéo signés et sous-titrés" },
  { cle: "accueil.lsf_cta", page: "Accueil", label: "Bloc LSF — bouton", valeur: "Découvrir l'atelier" },
  { cle: "accueil.apropos", page: "Accueil", label: "À propos", valeur: "Entre mes mains réunit trois univers qui se répondent : la naturopathie, pour comprendre et soutenir votre vitalité ; le massage bien-être, pour relâcher et accompagner les grands moments de la vie ; et les ateliers de signes associés à la parole, pour offrir à bébé ses premiers mots, avec les mains.\n\nUne approche douce, fondée sur l'écoute, le respect du rythme de chacun et des gestes précis, du tout-petit à l'adulte." },
  { cle: "accueil.apropos_cta", page: "Accueil", label: "À propos — bouton", valeur: "Me contacter" },
  { cle: "accueil.cta_final_titre", page: "Accueil", label: "CTA final — titre", valeur: "Prête à vous accorder ce moment ?" },
  { cle: "accueil.cta_final_texte", page: "Accueil", label: "CTA final — texte", valeur: "Réservez votre consultation ou votre massage en quelques clics — ou écrivez-moi pour en parler." },
  { cle: "accueil.cta_final_b1", page: "Accueil", label: "CTA final — bouton 1", valeur: "Réserver en ligne" },
  { cle: "accueil.cta_final_b2", page: "Accueil", label: "CTA final — bouton 2", valeur: "Poser une question" },

  // Naturo
  { cle: "naturo.badge", page: "Naturopathie", label: "Hero — pastille", valeur: "Consultations en visio" },
  { cle: "naturo.h1", page: "Naturopathie", label: "Hero — titre", valeur: "La naturopathie, en visio" },
  { cle: "naturo.intro", page: "Naturopathie", label: "Hero — introduction", valeur: "La naturopathie vise à soutenir votre vitalité et préserver votre équilibre grâce à des moyens naturels, en considérant la personne dans sa globalité. En visio, profitez d'un accompagnement personnalisé, où que vous soyez, dans le confort de votre environnement." },
  { cle: "naturo.cta", page: "Naturopathie", label: "Hero — bouton", valeur: "Réserver une consultation" },
  { cle: "naturo.access", page: "Naturopathie", label: "Hero — accessibilité", valeur: "Consultations accessibles aux personnes sourdes et malentendantes" },
  { cle: "naturo.approche_eyebrow", page: "Naturopathie", label: "Approche — petit titre", valeur: "L'approche" },
  { cle: "naturo.approche_titre", page: "Naturopathie", label: "Approche — titre", valeur: "Un accompagnement global et sur-mesure" },
  { cle: "naturo.approche1_titre", page: "Naturopathie", label: "Carte 1 — titre", valeur: "Vitalité au naturel" },
  { cle: "naturo.approche1_texte", page: "Naturopathie", label: "Carte 1 — texte", valeur: "Alimentation, hygiène de vie et gestion du stress : des conseils naturels et concrets, adaptés à votre quotidien, pour soutenir votre équilibre et votre vitalité." },
  { cle: "naturo.approche2_titre", page: "Naturopathie", label: "Carte 2 — titre", valeur: "Un plan personnalisé" },
  { cle: "naturo.approche2_texte", page: "Naturopathie", label: "Carte 2 — texte", valeur: "Une synthèse ainsi qu'un plan d'accompagnement personnalisé sont élaborés et vous sont envoyés sous 7 jours." },
  { cle: "naturo.approche3_titre", page: "Naturopathie", label: "Carte 3 — titre", valeur: "Un suivi dans le temps" },
  { cle: "naturo.approche3_texte", page: "Naturopathie", label: "Carte 3 — texte", valeur: "Des consultations de suivi pour ajuster, encourager et accompagner vos changements, saison après saison." },
  { cle: "naturo.deroule_eyebrow", page: "Naturopathie", label: "Déroulé — petit titre", valeur: "Le déroulé" },
  { cle: "naturo.deroule_titre", page: "Naturopathie", label: "Déroulé — titre", valeur: "Comment se passent les consultations ?" },
  { cle: "naturo.d1_titre", page: "Naturopathie", label: "Déroulé 1 — titre", valeur: "Le premier rendez-vous" },
  { cle: "naturo.d1_detail", page: "Naturopathie", label: "Déroulé 1 — durée", valeur: "1h30 maximum" },
  { cle: "naturo.d1_texte", page: "Naturopathie", label: "Déroulé 1 — texte", valeur: "Un bilan de vitalité complet : votre histoire, vos habitudes, vos ressentis. L'occasion de faire le point, en profondeur." },
  { cle: "naturo.d2_titre", page: "Naturopathie", label: "Déroulé 2 — titre", valeur: "Des conseils personnalisés" },
  { cle: "naturo.d2_detail", page: "Naturopathie", label: "Déroulé 2 — délai", valeur: "sous 7 jours" },
  { cle: "naturo.d2_texte", page: "Naturopathie", label: "Déroulé 2 — texte", valeur: "Une synthèse et un plan d'accompagnement personnalisé vous sont envoyés sous 7 jours." },
  { cle: "naturo.d3_titre", page: "Naturopathie", label: "Déroulé 3 — titre", valeur: "Les suivis" },
  { cle: "naturo.d3_detail", page: "Naturopathie", label: "Déroulé 3 — durée", valeur: "1h" },
  { cle: "naturo.d3_texte", page: "Naturopathie", label: "Déroulé 3 — texte", valeur: "Pour ajuster les recommandations, constater les progrès et traverser les changements de saison en douceur." },
  { cle: "naturo.visio_titre", page: "Naturopathie", label: "Encadré visio — titre", valeur: "100 % en visio — sans rien à installer" },
  { cle: "naturo.visio_texte", page: "Naturopathie", label: "Encadré visio — texte", valeur: "Le lien de visioconférence vous est envoyé automatiquement après votre réservation, et un rappel vous est adressé la veille. Prévoyez simplement un endroit calme et une bonne connexion." },
  { cle: "naturo.tarifs_eyebrow", page: "Naturopathie", label: "Tarifs — petit titre", valeur: "Tarifs" },
  { cle: "naturo.tarifs_titre", page: "Naturopathie", label: "Tarifs — titre", valeur: "Des tarifs simples et transparents" },
  { cle: "naturo.tarifs_sous", page: "Naturopathie", label: "Tarifs — sous-titre", valeur: "Paiement intégral en ligne à la réservation." },

  // Massages page + accordion
  { cle: "massages.badge", page: "Massages", label: "Hero — pastille", valeur: "Massages à domicile" },
  { cle: "massages.h1", page: "Massages", label: "Hero — titre", valeur: "Le bien-être, chez vous" },
  { cle: "massages.intro", page: "Massages", label: "Hero — introduction", valeur: "Je me déplace à votre domicile avec tout le matériel : massages prénatal, postnatal et bébé, au rythme de chacun." },
  { cle: "massages.cta", page: "Massages", label: "Hero — bouton", valeur: "Réserver un massage" },
  { cle: "massages.access", page: "Massages", label: "Hero — accessibilité", valeur: "Massages accessibles aux personnes sourdes et malentendantes" },
  { cle: "massages.liste_eyebrow", page: "Massages", label: "Liste — petit titre", valeur: "Les massages" },
  { cle: "massages.liste_titre", page: "Massages", label: "Liste — titre", valeur: "Choisissez le moment qui vous correspond" },
  { cle: "massages.liste_sous", page: "Massages", label: "Liste — sous-titre", valeur: "Cliquez sur un massage pour découvrir son déroulé, sa durée et les précautions." },
  { cle: "massages.duree_prefixe", page: "Massages", label: "Encadré — préfixe durée", valeur: "Durée indicative :" },
  { cle: "massages.reserver_ce", page: "Massages", label: "Bouton dans l'encadré", valeur: "Réserver ce massage" },
  { cle: "massages.provisoire", page: "Massages", label: "Mention sous la liste", valeur: "Tarifs et durées provisoires — les valeurs définitives seront affichées prochainement." },

  { cle: "massages.prenatal.titre", page: "Massages", label: "Prénatal — titre", valeur: "Massage bien-être prénatal" },
  { cle: "massages.prenatal.accroche", page: "Massages", label: "Prénatal — sous-encadré", valeur: "À partir du 4e mois — un relâchement du dos, centré sur votre bien-être." },
  { cle: "massages.prenatal.duree", page: "Massages", label: "Prénatal — durée", valeur: "1h15" },
  { cle: "massages.prenatal.d1", page: "Massages", label: "Prénatal — paragraphe 1", valeur: "C'est un massage relaxant : il apaise le système nerveux, libère le stress, l'angoisse et la fatigue, et soulage différents maux de la grossesse." },
  { cle: "massages.prenatal.d2", page: "Massages", label: "Prénatal — paragraphe 2", valeur: "C'est un relâchement total, une pause centrée sur votre bien-être et une connexion à votre corps en plein changement." },
  { cle: "massages.prenatal.d3", page: "Massages", label: "Prénatal — paragraphe 3", valeur: "Il s'agit d'un massage du dos afin de préserver votre intimité (toutes les femmes n'aiment pas être touchées au ventre, lieu de vie de leur bébé)." },
  { cle: "massages.prenatal.d4", page: "Massages", label: "Prénatal — paragraphe 4", valeur: "Le massage se fait allongée sur le côté, avec une huile végétale bio et sans huile essentielle." },
  { cle: "massages.prenatal.bloc_titre", page: "Massages", label: "Prénatal — titre encadré précautions", valeur: "Massage bien-être prénatal" },
  { cle: "massages.prenatal.p1", page: "Massages", label: "Prénatal — précaution 1", valeur: "Le massage prénatal est proposé à partir du 4e mois de grossesse, dans le cadre d'une grossesse ne présentant pas de contre-indication particulière." },
  { cle: "massages.prenatal.p2", page: "Massages", label: "Prénatal — précaution 2", valeur: "En cas de grossesse à risque, complication, suivi médical particulier, symptômes inhabituels ou doute concernant la possibilité de recevoir un massage, un avis favorable du médecin ou de la sage-femme sera demandé avant la séance." },
  { cle: "massages.prenatal.p3", page: "Massages", label: "Prénatal — précaution 3", valeur: "La future maman s'engage à communiquer toute information utile concernant sa grossesse et son état de santé." },

  { cle: "massages.postnatal.titre", page: "Massages", label: "Postnatal — titre", valeur: "Massage bien-être postnatal" },
  { cle: "massages.postnatal.accroche", page: "Massages", label: "Postnatal — sous-encadré", valeur: "Pour toute femme dont le corps a porté la vie — récemment ou il y a longtemps." },
  { cle: "massages.postnatal.duree", page: "Massages", label: "Postnatal — durée", valeur: "1h30" },
  { cle: "massages.postnatal.d1", page: "Massages", label: "Postnatal — paragraphe 1", valeur: "Pour la femme après l'accouchement, et aussi pour celle qui a donné naissance il y a des années. Celles dont le corps, le féminin, a traversé des violences, une fausse couche, une IVG/IMG, une PMA, une transition de vie — ou simplement le désir de se reconnecter à son corps." },
  { cle: "massages.postnatal.d2", page: "Massages", label: "Postnatal — paragraphe 2", valeur: "Le massage soulage les tensions, nourrit la peau, aide à lâcher-prise, évacuer le stress et relancer les énergies." },
  { cle: "massages.postnatal.d3", page: "Massages", label: "Postnatal — paragraphe 3", valeur: "Il s'agit d'un massage du dos et des bras, à l'huile végétale bio et sans huile essentielle." },
  { cle: "massages.postnatal.d4", page: "Massages", label: "Postnatal — paragraphe 4", valeur: "Outils utilisés : bol tibétain, diapason, rebozo." },
  { cle: "massages.postnatal.bloc_titre", page: "Massages", label: "Postnatal — titre encadré précautions", valeur: "Massage bien-être postnatal" },
  { cle: "massages.postnatal.p1", page: "Massages", label: "Postnatal — précaution 1", valeur: "Le massage postnatal est proposé à partir de 6 semaines après l'accouchement, sous réserve d'une récupération normale et de l'absence de contre-indication." },
  { cle: "massages.postnatal.p2", page: "Massages", label: "Postnatal — précaution 2", valeur: "En cas de césarienne, complication post-partum, cicatrisation en cours, infection, fièvre, douleur inexpliquée ou problème de santé particulier, la séance pourra être reportée et un avis médical demandé avant sa réalisation." },
  { cle: "massages.postnatal.p3", page: "Massages", label: "Postnatal — précaution 3", valeur: "La cliente s'engage à signaler toute information concernant son accouchement, son post-partum ou son état de santé susceptible de nécessiter une précaution particulière." },

  { cle: "massages.bebe.titre", page: "Massages", label: "Bébé — titre", valeur: "Massage bien-naître pour bébé" },
  { cle: "massages.bebe.accroche", page: "Massages", label: "Bébé — sous-encadré", valeur: "En individuel, à domicile — vous choisissez le thème de la séance." },
  { cle: "massages.bebe.duree", page: "Massages", label: "Bébé — durée", valeur: "1h à 2h" },
  { cle: "massages.bebe.d1", page: "Massages", label: "Bébé — paragraphe 1", valeur: "Le massage libère les hormones du bien-être, favorise l'éveil des sens, le calme, l'endormissement et le soulagement. C'est se connecter l'un à l'autre et être à l'écoute de son bébé." },
  { cle: "massages.bebe.d2", page: "Massages", label: "Bébé — paragraphe 2", valeur: "Thèmes au choix : pour bien dormir ; pour l'éveil moteur ; spécifique maux de ventre ; libérer les émotions." },
  { cle: "massages.bebe.d3", page: "Massages", label: "Bébé — paragraphe 3", valeur: "La séance comprend un temps d'échange avec le(s) parent(s), un temps autour du thème choisi, l'apprentissage et la pratique du massage, puis des postures de baby yoga en fin de séance." },
  { cle: "massages.bebe.d4", page: "Massages", label: "Bébé — paragraphe 4", valeur: "Lors de l'atelier, je réalise les gestes de massage sur un poupon de démonstration. À aucun moment je ne masse votre bébé. Vous reproduisez vous-même les mouvements sur votre enfant, à son rythme, en suivant mes indications." },

  { cle: "massages.forfait.titre", page: "Massages", label: "Forfait bébé — titre", valeur: "Massage bébé — forfait 4 séances" },
  { cle: "massages.forfait.accroche", page: "Massages", label: "Forfait bébé — sous-encadré", valeur: "Un accompagnement complet pour suivre l'évolution de bébé." },
  { cle: "massages.forfait.duree", page: "Massages", label: "Forfait bébé — durée", valeur: "4 × 1h à 2h" },
  { cle: "massages.forfait.d1", page: "Massages", label: "Forfait bébé — paragraphe 1", valeur: "Le massage bébé est un rituel précieux qui crée du lien, apaise, soutient le bien physique et émotionnel de votre enfant à chaque étape." },
  { cle: "massages.forfait.d2", page: "Massages", label: "Forfait bébé — paragraphe 2", valeur: "Le forfait permet de suivre l'évolution de bébé, d'adapter les massages à ses besoins et d'installer un rituel durable. Soit 70 € la séance." },
  { cle: "massages.forfait.d3", page: "Massages", label: "Forfait bébé — paragraphe 3", valeur: "Chaque séance : échange avec le(s) parent(s), thème choisi, apprentissage du massage, postures de baby yoga." },
  { cle: "massages.forfait.d4", page: "Massages", label: "Forfait bébé — paragraphe 4", valeur: "Lors de l'atelier, je réalise les gestes de massage sur un poupon de démonstration. À aucun moment je ne masse votre bébé. Vous reproduisez vous-même les mouvements sur votre enfant, à son rythme, en suivant mes indications." },

  { cle: "massages.bebe.bloc_titre", page: "Massages", label: "Encadré bébé — titre", valeur: "Massage bien-naître bébé" },
  { cle: "massages.bebe.p1", page: "Massages", label: "Encadré bébé — puce 1", valeur: "La séance est adaptée au rythme et aux besoins de bébé." },
  { cle: "massages.bebe.p2", page: "Massages", label: "Encadré bébé — puce 2", valeur: "Par mesure de précaution, le massage sera reporté en cas de maladie, fièvre, infection, état inhabituel de bébé ou vaccination récente." },
  { cle: "massages.bebe.p3", page: "Massages", label: "Encadré bébé — puce 3", valeur: "En présence d'un problème de santé particulier ou en cas de doute, l'avis d'un professionnel de santé pourra être demandé avant la séance." },
  { cle: "massages.bebe.p4", page: "Massages", label: "Encadré bébé — puce 4", valeur: "Le(s) parent(s) s'engage(nt) à signaler toute information concernant la santé de son enfant susceptible de nécessiter une précaution ou de constituer une contre-indication au massage." },

  { cle: "massages.general.titre", page: "Massages", label: "Encadré général — titre", valeur: "Informations importantes – Précautions & contre-indications" },
  { cle: "massages.general.p1", page: "Massages", label: "Encadré général — texte", valeur: "Les massages proposés sont exclusivement des massages de bien-être à visée de détente et de relaxation. Ils ne constituent ni un acte médical, ni un soin thérapeutique et ne se substituent en aucun cas à un diagnostic, un traitement ou un suivi par un professionnel de santé." },
  { cle: "massages.resp.titre", page: "Massages", label: "Encadré responsabilité — titre", valeur: "Responsabilité & sécurité" },
  { cle: "massages.resp.p1", page: "Massages", label: "Encadré responsabilité — puce 1", valeur: "Il appartient au bénéficiaire de la prestation — ou au représentant légal lorsqu'il s'agit d'un enfant — de communiquer avant la séance toute information de santé pertinente, tout traitement en cours et toute contre-indication connue." },
  { cle: "massages.resp.p2", page: "Massages", label: "Encadré responsabilité — puce 2", valeur: "En cas de doute concernant la compatibilité de la prestation avec l'état de santé de la personne ou de l'enfant, la séance pourra être différée dans l'attente de l'avis d'un professionnel de santé." },
  { cle: "massages.resp.p3", page: "Massages", label: "Encadré responsabilité — puce 3", valeur: "La priorité reste à chaque instant la sécurité, le confort et le bien-être de la personne massée." },

  { cle: "massages.zone_badge", page: "Massages", label: "Zone — pastille", valeur: "Zone de déplacement" },
  { cle: "massages.zone_titre", page: "Massages", label: "Zone — titre", valeur: "Un supplément kilométrique transparent" },
  { cle: "massages.zone_texte1", page: "Massages", label: "Zone — paragraphe 1", valeur: "Les 15 premiers kilomètres sont inclus dans le prix de la séance. Au-delà, comptez 0,55 € par kilomètre parcouru." },
  { cle: "massages.zone_texte2", page: "Massages", label: "Zone — paragraphe 2", valeur: "Lors de la réservation, le supplément est calculé automatiquement depuis votre adresse exacte : vous validez en toute connaissance du montant final." },
  { cle: "massages.zone_cta2", page: "Massages", label: "Zone — bouton question", valeur: "Une question sur la zone ?" },
  { cle: "massages.zone_apercu", page: "Massages", label: "Zone — encadré", valeur: "Estimer le supplément" },
  { cle: "massages.pratique1_titre", page: "Massages", label: "Pratique 1 — titre", valeur: "Tout le matériel est prévu" },
  { cle: "massages.pratique1_texte", page: "Massages", label: "Pratique 1 — texte", valeur: "Table, huiles, musique, serviettes : je viens avec tout." },
  { cle: "massages.pratique2_titre", page: "Massages", label: "Pratique 2 — titre", valeur: "Votre cocon, chez vous" },
  { cle: "massages.pratique2_texte", page: "Massages", label: "Pratique 2 — texte", valeur: "La séance s'installe dans votre salon : lumière tamisée, calme, chaleur." },
  { cle: "massages.pratique3_titre", page: "Massages", label: "Pratique 3 — titre", valeur: "Il suffit d'un espace calme" },
  { cle: "massages.pratique3_texte", page: "Massages", label: "Pratique 3 — texte", valeur: "Une pièce au calme et environ une heure devant vous : c'est tout ce qu'il faut." },

  // LSF
  { cle: "lsf.h1", page: "Bébé signes", label: "Hero — titre", valeur: "Offrir à bébé ses premiers mots, avec les mains" },
  { cle: "lsf.intro", page: "Bébé signes", label: "Hero — introduction", valeur: "Bien avant la parole, votre bébé a déjà beaucoup à exprimer : une faim, une envie de câlin, une fatigue… La langue des signes française lui donne un moyen simple et naturel de se faire comprendre. Au fil de l'atelier, vous apprendrez les signes essentiels du quotidien de votre bébé et la manière de les intégrer en douceur à vos échanges, à votre rythme." },
  { cle: "lsf.cta", page: "Bébé signes", label: "Hero — bouton", valeur: "Réserver l'atelier" },
  { cle: "lsf.pourquoi_eyebrow", page: "Bébé signes", label: "Pourquoi — petit titre", valeur: "Pourquoi signer ?" },
  { cle: "lsf.pourquoi_titre", page: "Bébé signes", label: "Pourquoi — titre", valeur: "Des signes simples, de grands effets" },
  { cle: "lsf.b1_titre", page: "Bébé signes", label: "Bienfait 1 — titre", valeur: "Moins de frustrations" },
  { cle: "lsf.b1_texte", page: "Bébé signes", label: "Bienfait 1 — texte", valeur: "Bébé peut exprimer faim, fatigue ou envie de câlin avant de savoir parler — et être entendu." },
  { cle: "lsf.b2_titre", page: "Bébé signes", label: "Bienfait 2 — titre", valeur: "Un lien renforcé" },
  { cle: "lsf.b2_texte", page: "Bébé signes", label: "Bienfait 2 — texte", valeur: "Signer avec bébé, c'est un jeu de regards et de signes partagés, au cœur du quotidien." },
  { cle: "lsf.b3_titre", page: "Bébé signes", label: "Bienfait 3 — titre", valeur: "Le plaisir avant la performance" },
  { cle: "lsf.b3_texte", page: "Bébé signes", label: "Bienfait 3 — texte", valeur: "L'atelier est un moment joyeux : on y apprend quelques signes essentiels, à son rythme, sans pression." },
  { cle: "lsf.formats_eyebrow", page: "Bébé signes", label: "Formats — petit titre", valeur: "Les formats" },
  { cle: "lsf.formats_titre", page: "Bébé signes", label: "Formats — titre", valeur: "Trois façons de suivre l'atelier" },
  { cle: "lsf.formats_sous", page: "Bébé signes", label: "Formats — sous-titre", valeur: "Choisissez le format qui convient à votre famille et aux professionnels* de la petite enfance : à domicile, en collectif ou en visio." },
  { cle: "lsf.f1_titre", page: "Bébé signes", label: "Format domicile — titre", valeur: "À domicile" },
  { cle: "lsf.f1_texte", page: "Bébé signes", label: "Format domicile — texte", valeur: "L'atelier se déroule chez vous, dans le cocon de bébé. Le supplément kilométrique s'applique selon la zone de déplacement (15 km inclus, puis 0,55 €/km)." },
  { cle: "lsf.f2_titre", page: "Bébé signes", label: "Format collectif — titre", valeur: "En collectif (présentiel)" },
  { cle: "lsf.f2_texte", page: "Bébé signes", label: "Format collectif — texte", valeur: "Un petit groupe de familles, dans un lieu dédié. Les places sont limitées pour préserver la qualité des échanges." },
  { cle: "lsf.f3_titre", page: "Bébé signes", label: "Format visio — titre", valeur: "En visio" },
  { cle: "lsf.f3_texte", page: "Bébé signes", label: "Format visio — texte", valeur: "Depuis chez vous, avec un lien de visioconférence envoyé automatiquement après réservation. Idéal sans déplacement." },
  { cle: "lsf.formats_note", page: "Bébé signes", label: "Formats — note professionnels", valeur: "* Pour les professionnels de la petite enfance, un devis sera envoyé." },
  { cle: "lsf.tarifs_eyebrow", page: "Bébé signes", label: "Tarifs — petit titre", valeur: "Tarifs & formules" },
  { cle: "lsf.tarifs_titre", page: "Bébé signes", label: "Tarifs — titre", valeur: "À l'unité ou en forfait" },
  { cle: "lsf.tarifs_sous", page: "Bébé signes", label: "Tarifs — sous-titre", valeur: "Prix provisoires, à confirmer — chaque formule est valable pour les formats domicile, collectif et visio." },

  // Contact + pied
  { cle: "contact.eyebrow", page: "Contact", label: "Petit titre", valeur: "Contact" },
  { cle: "contact.titre", page: "Contact", label: "Titre", valeur: "Une question ? Parlons-en" },
  { cle: "contact.sous", page: "Contact", label: "Sous-titre", valeur: "Un doute sur une prestation, une demande particulière, un créneau spécifique : écrivez-moi, je réponds rapidement." },
  { cle: "footer.texte", page: "Pied de page", label: "Texte sous le logo", valeur: "Naturopathie · massages · bébé signes. Consultations en visio, massages à domicile pour vous et pour bébé, atelier de langue des signes française." },
  { cle: "footer.access", page: "Pied de page", label: "Accessibilité", valeur: "Prestations accessibles aux personnes sourdes et malentendantes" },
  { cle: "footer.activites", page: "Pied de page", label: "Colonne activités", valeur: "Activités — au service de la femme" },
  { cle: "footer.infos", page: "Pied de page", label: "Colonne informations", valeur: "Informations" },
];

export function texteDefaut(cle: string) {
  return TEXTES_DEFAUT.find((row) => row.cle === cle)?.valeur || "";
}

export function t(map: Record<string, string>, cle: string) {
  const v = (map[cle] || "").trim();
  return v || texteDefaut(cle);
}
